// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJep8oxL4s7ilia5gc1ckoEg1EBv6GURE',
    appId: '1:431945182352:web:3e4836610f0d559610bc15',
    messagingSenderId: '431945182352',
    projectId: 'smart-ti-polnes-bbe34',
    authDomain: 'smart-ti-polnes-bbe34.firebaseapp.com',
    databaseURL: 'https://smart-ti-polnes-bbe34-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-ti-polnes-bbe34.appspot.com',
    measurementId: 'G-1LN95RW39Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs8b7L3fov55tVw3j9O8PaQ9r5_YG4vKY',
    appId: '1:431945182352:android:55b70c12d4cb7f8710bc15',
    messagingSenderId: '431945182352',
    projectId: 'smart-ti-polnes-bbe34',
    databaseURL: 'https://smart-ti-polnes-bbe34-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-ti-polnes-bbe34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHQ6oTM7zHeiAUZ8lVaGJjx76koYDACmQ',
    appId: '1:431945182352:ios:8ffeb3a43f811d1010bc15',
    messagingSenderId: '431945182352',
    projectId: 'smart-ti-polnes-bbe34',
    databaseURL: 'https://smart-ti-polnes-bbe34-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-ti-polnes-bbe34.appspot.com',
    iosClientId: '431945182352-1t0amue7e4o9sv0lmjgtpavja7gtt3pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartPolnes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHQ6oTM7zHeiAUZ8lVaGJjx76koYDACmQ',
    appId: '1:431945182352:ios:8ffeb3a43f811d1010bc15',
    messagingSenderId: '431945182352',
    projectId: 'smart-ti-polnes-bbe34',
    databaseURL: 'https://smart-ti-polnes-bbe34-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-ti-polnes-bbe34.appspot.com',
    iosClientId: '431945182352-1t0amue7e4o9sv0lmjgtpavja7gtt3pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartPolnes',
  );
}
